---
- name: Installing Apache
  apt:
    name: apache2
    state: latest
  notify: restart_apache

- name: copy index.html file
  copy:
    src: index.html
    dest: "/var/www/html/"
  notify: restart_apache

# tasks file for apache_role/
